// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(stead_ffiFFI)
import stead_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_stead_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_stead_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct FfiContract {
    public var id: String
    public var projectPath: String
    public var task: String
    public var verification: String
    public var status: FfiContractStatus
    public var createdAt: String
    public var completedAt: String?
    public var output: String?
    public var owner: String?
    public var blockedBy: [String]
    public var blocks: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, projectPath: String, task: String, verification: String, status: FfiContractStatus, createdAt: String, completedAt: String?, output: String?, owner: String?, blockedBy: [String], blocks: [String]) {
        self.id = id
        self.projectPath = projectPath
        self.task = task
        self.verification = verification
        self.status = status
        self.createdAt = createdAt
        self.completedAt = completedAt
        self.output = output
        self.owner = owner
        self.blockedBy = blockedBy
        self.blocks = blocks
    }
}



extension FfiContract: Equatable, Hashable {
    public static func ==(lhs: FfiContract, rhs: FfiContract) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.projectPath != rhs.projectPath {
            return false
        }
        if lhs.task != rhs.task {
            return false
        }
        if lhs.verification != rhs.verification {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.completedAt != rhs.completedAt {
            return false
        }
        if lhs.output != rhs.output {
            return false
        }
        if lhs.owner != rhs.owner {
            return false
        }
        if lhs.blockedBy != rhs.blockedBy {
            return false
        }
        if lhs.blocks != rhs.blocks {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(projectPath)
        hasher.combine(task)
        hasher.combine(verification)
        hasher.combine(status)
        hasher.combine(createdAt)
        hasher.combine(completedAt)
        hasher.combine(output)
        hasher.combine(owner)
        hasher.combine(blockedBy)
        hasher.combine(blocks)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiContract: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiContract {
        return
            try FfiContract(
                id: FfiConverterString.read(from: &buf), 
                projectPath: FfiConverterString.read(from: &buf), 
                task: FfiConverterString.read(from: &buf), 
                verification: FfiConverterString.read(from: &buf), 
                status: FfiConverterTypeFfiContractStatus.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                completedAt: FfiConverterOptionString.read(from: &buf), 
                output: FfiConverterOptionString.read(from: &buf), 
                owner: FfiConverterOptionString.read(from: &buf), 
                blockedBy: FfiConverterSequenceString.read(from: &buf), 
                blocks: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiContract, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.projectPath, into: &buf)
        FfiConverterString.write(value.task, into: &buf)
        FfiConverterString.write(value.verification, into: &buf)
        FfiConverterTypeFfiContractStatus.write(value.status, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.completedAt, into: &buf)
        FfiConverterOptionString.write(value.output, into: &buf)
        FfiConverterOptionString.write(value.owner, into: &buf)
        FfiConverterSequenceString.write(value.blockedBy, into: &buf)
        FfiConverterSequenceString.write(value.blocks, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiContract_lift(_ buf: RustBuffer) throws -> FfiContract {
    return try FfiConverterTypeFfiContract.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiContract_lower(_ value: FfiContract) -> RustBuffer {
    return FfiConverterTypeFfiContract.lower(value)
}


public struct FfiSessionSummary {
    public var id: String
    public var cli: FfiCliType
    public var projectPath: String
    public var title: String
    public var created: String
    public var lastModified: String
    public var messageCount: UInt32
    public var gitBranch: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, cli: FfiCliType, projectPath: String, title: String, created: String, lastModified: String, messageCount: UInt32, gitBranch: String?) {
        self.id = id
        self.cli = cli
        self.projectPath = projectPath
        self.title = title
        self.created = created
        self.lastModified = lastModified
        self.messageCount = messageCount
        self.gitBranch = gitBranch
    }
}



extension FfiSessionSummary: Equatable, Hashable {
    public static func ==(lhs: FfiSessionSummary, rhs: FfiSessionSummary) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.cli != rhs.cli {
            return false
        }
        if lhs.projectPath != rhs.projectPath {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.created != rhs.created {
            return false
        }
        if lhs.lastModified != rhs.lastModified {
            return false
        }
        if lhs.messageCount != rhs.messageCount {
            return false
        }
        if lhs.gitBranch != rhs.gitBranch {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(cli)
        hasher.combine(projectPath)
        hasher.combine(title)
        hasher.combine(created)
        hasher.combine(lastModified)
        hasher.combine(messageCount)
        hasher.combine(gitBranch)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSessionSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSessionSummary {
        return
            try FfiSessionSummary(
                id: FfiConverterString.read(from: &buf), 
                cli: FfiConverterTypeFfiCliType.read(from: &buf), 
                projectPath: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                lastModified: FfiConverterString.read(from: &buf), 
                messageCount: FfiConverterUInt32.read(from: &buf), 
                gitBranch: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSessionSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterTypeFfiCliType.write(value.cli, into: &buf)
        FfiConverterString.write(value.projectPath, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.lastModified, into: &buf)
        FfiConverterUInt32.write(value.messageCount, into: &buf)
        FfiConverterOptionString.write(value.gitBranch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionSummary_lift(_ buf: RustBuffer) throws -> FfiSessionSummary {
    return try FfiConverterTypeFfiSessionSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionSummary_lower(_ value: FfiSessionSummary) -> RustBuffer {
    return FfiConverterTypeFfiSessionSummary.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiCliType {
    
    case claude
    case codex
    case openCode
    case universal
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCliType: FfiConverterRustBuffer {
    typealias SwiftType = FfiCliType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCliType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .claude
        
        case 2: return .codex
        
        case 3: return .openCode
        
        case 4: return .universal
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCliType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .claude:
            writeInt(&buf, Int32(1))
        
        
        case .codex:
            writeInt(&buf, Int32(2))
        
        
        case .openCode:
            writeInt(&buf, Int32(3))
        
        
        case .universal:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCliType_lift(_ buf: RustBuffer) throws -> FfiCliType {
    return try FfiConverterTypeFfiCliType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCliType_lower(_ value: FfiCliType) -> RustBuffer {
    return FfiConverterTypeFfiCliType.lower(value)
}



extension FfiCliType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiContractStatus {
    
    case pending
    case ready
    case claimed
    case executing
    case verifying
    case completed
    case failed
    case rollingBack
    case rolledBack
    case cancelled
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiContractStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiContractStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiContractStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pending
        
        case 2: return .ready
        
        case 3: return .claimed
        
        case 4: return .executing
        
        case 5: return .verifying
        
        case 6: return .completed
        
        case 7: return .failed
        
        case 8: return .rollingBack
        
        case 9: return .rolledBack
        
        case 10: return .cancelled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiContractStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pending:
            writeInt(&buf, Int32(1))
        
        
        case .ready:
            writeInt(&buf, Int32(2))
        
        
        case .claimed:
            writeInt(&buf, Int32(3))
        
        
        case .executing:
            writeInt(&buf, Int32(4))
        
        
        case .verifying:
            writeInt(&buf, Int32(5))
        
        
        case .completed:
            writeInt(&buf, Int32(6))
        
        
        case .failed:
            writeInt(&buf, Int32(7))
        
        
        case .rollingBack:
            writeInt(&buf, Int32(8))
        
        
        case .rolledBack:
            writeInt(&buf, Int32(9))
        
        
        case .cancelled:
            writeInt(&buf, Int32(10))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiContractStatus_lift(_ buf: RustBuffer) throws -> FfiContractStatus {
    return try FfiConverterTypeFfiContractStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiContractStatus_lower(_ value: FfiContractStatus) -> RustBuffer {
    return FfiConverterTypeFfiContractStatus.lower(value)
}



extension FfiContractStatus: Equatable, Hashable {}




public enum FfiError {

    
    
    case Storage(message: String
    )
    case NotFound(id: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotFound(
            id: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Storage(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .NotFound(id):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(id, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiContract: FfiConverterRustBuffer {
    typealias SwiftType = [FfiContract]

    public static func write(_ value: [FfiContract], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiContract.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiContract] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiContract]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiContract.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiSessionSummary: FfiConverterRustBuffer {
    typealias SwiftType = [FfiSessionSummary]

    public static func write(_ value: [FfiSessionSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiSessionSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiSessionSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiSessionSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiSessionSummary.read(from: &buf))
        }
        return seq
    }
}
public func cancelContract(id: String, cwd: String)throws  -> FfiContract {
    return try  FfiConverterTypeFfiContract.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_stead_ffi_fn_func_cancel_contract(
        FfiConverterString.lower(id),
        FfiConverterString.lower(cwd),$0
    )
})
}
public func claimContract(id: String, owner: String, cwd: String)throws  -> FfiContract {
    return try  FfiConverterTypeFfiContract.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_stead_ffi_fn_func_claim_contract(
        FfiConverterString.lower(id),
        FfiConverterString.lower(owner),
        FfiConverterString.lower(cwd),$0
    )
})
}
public func getContract(id: String, cwd: String)throws  -> FfiContract {
    return try  FfiConverterTypeFfiContract.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_stead_ffi_fn_func_get_contract(
        FfiConverterString.lower(id),
        FfiConverterString.lower(cwd),$0
    )
})
}
public func listContracts(cwd: String)throws  -> [FfiContract] {
    return try  FfiConverterSequenceTypeFfiContract.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_stead_ffi_fn_func_list_contracts(
        FfiConverterString.lower(cwd),$0
    )
})
}
public func listSessions(cliFilter: String?, project: String?, limit: UInt32) -> [FfiSessionSummary] {
    return try!  FfiConverterSequenceTypeFfiSessionSummary.lift(try! rustCall() {
    uniffi_stead_ffi_fn_func_list_sessions(
        FfiConverterOptionString.lower(cliFilter),
        FfiConverterOptionString.lower(project),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
public func verifyContract(id: String, cwd: String)throws  -> FfiContract {
    return try  FfiConverterTypeFfiContract.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_stead_ffi_fn_func_verify_contract(
        FfiConverterString.lower(id),
        FfiConverterString.lower(cwd),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_stead_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_stead_ffi_checksum_func_cancel_contract() != 61552) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stead_ffi_checksum_func_claim_contract() != 27115) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stead_ffi_checksum_func_get_contract() != 39411) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stead_ffi_checksum_func_list_contracts() != 60386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stead_ffi_checksum_func_list_sessions() != 8745) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stead_ffi_checksum_func_verify_contract() != 12713) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all